name: "Gsmarena"
main_url: "http://www.gsmarena.com/"
brands_url: "makers.php3"
brand_link_path: ".st-text table tr td:nth-child(1) a, .st-text table tr td:nth-child(3) a"
brand_name_item: "./img"
brand_source: "alt"
model_link_path: ".makers ul li a"
model_image_item: "./img"
model_name_item: "./strong/span"
spec_path: "#specs-list table tr"
spec_type_item: "./th"
spec_category_item: "td.ttl"
spec_body_item: "td.nfo"
next_page: "a.pages-next"
search_page: "results.php3?sQuickSearch=yes&sName="